"""initial

Revision ID: 0001
Revises:
Create Date: 2026-09-23 16:07:08.272447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rehearsal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('samplerate', sa.Integer(), nullable=False),
    sa.Column('bit_depth', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder')
    )
    op.create_table('take',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rehearsal_id', sa.Integer(), nullable=False),
    sa.Column('take_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('cloud_skip', sa.Boolean(), nullable=False),
    sa.Column('cloud_send', sa.Boolean(), nullable=False),
    sa.Column('cloud_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rehearsal_id'], ['rehearsal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rehearsal_id', 'take_number')
    )
    with op.batch_alter_table('take', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_take_rehearsal_id'), ['rehearsal_id'], unique=False)

    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rehearsal_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rehearsal_id'], ['rehearsal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_rehearsal_id'), ['rehearsal_id'], unique=False)

    op.create_table('cloud_copy',
    sa.Column('take_id', sa.Integer(), nullable=False),
    sa.Column('mix', sa.String(), nullable=True),
    sa.Column('mix_format', sa.String(), nullable=True),
    sa.Column('gain', sa.Float(), nullable=True),
    sa.Column('tracks', sa.String(), nullable=True),
    sa.Column('tracks_format', sa.String(), nullable=True),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['take_id'], ['take.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('take_id')
    )
    op.create_table('marker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('take_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['take_id'], ['take.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marker_take_id'), ['take_id'], unique=False)

    op.create_table('take_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('take_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['take_id'], ['take.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('take_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_take_file_take_id'), ['take_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('take_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_take_file_take_id'))

    op.drop_table('take_file')
    with op.batch_alter_table('marker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marker_take_id'))

    op.drop_table('marker')
    op.drop_table('cloud_copy')
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_rehearsal_id'))

    op.drop_table('track')
    with op.batch_alter_table('take', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_take_rehearsal_id'))

    op.drop_table('take')
    op.drop_table('rehearsal')
    # ### end Alembic commands ###
